@baseUrl = http://localhost:8080

### users (limit 1000)
GET {{baseUrl}}/hello/users?limit=0

### user by id
GET {{baseUrl}}/hello/users/0

### posts (limit 1000)
GET {{baseUrl}}/hello/posts

### post by id
GET {{baseUrl}}/hello/posts/0